spring.application.name=RutaExpress
spring.datasource.url=jdbc:postgresql://localhost/envios_db
spring.datasource.username=postgres
feature-geolocalizacion
spring.datasource.password=admin


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

app.repartidor.meta-diaria=5
app.repartidor.plazo-entrega-horas=24
app.repartidor.max-intentos-entrega=3
