spring.application.name=RutaExpress
spring.datasouerce.url=jdbc:postgresql://localhost/envios_db
spring.datasouerce.username=postgres
spring.datasouerce.password=1231

spring.datasouerce.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
